#!/usr/local/bin/perl

#
# Copyright (c) by Kirill Miazine <km@krot.org>
#
# This software is distributed under an ISC-style license, please see
# <http://km.krot.org/code/license.txt> for details.
#

use lib qw(
  ../lib
    /local/perl
    /local/perl5/lib/perl5
    /local/perl5/lib/perl5/amd64-freebsd
);

use Mojolicious::Lite;
app->plugin('yubi_verify',
  api_id => 1851,
  api_key => 'oBVbNt7IZehZGR99rvq8d6RZ1DM=',
);
get '/:otp' => sub {
  my $self = shift;
  my $otp = $self->stash('otp');
  my ($key, $res) = $self->yubi_verify($otp, 1);
  say Data::Dumper::Dumper($res);
  $self->render_text($key ."\n". Data::Dumper::Dumper($res));
};

app->start;
